name: CD

on:
  workflow_dispatch:
  release:
    types:
      - publish

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: pipx run build

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*
